/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GtkLabel {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLGtkLabelElement extends Components.GtkLabel, HTMLStencilElement {
    }
    var HTMLGtkLabelElement: {
        prototype: HTMLGtkLabelElement;
        new (): HTMLGtkLabelElement;
    };
    interface HTMLElementTagNameMap {
        "gtk-label": HTMLGtkLabelElement;
    }
}
declare namespace LocalJSX {
    interface GtkLabel {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "gtk-label": GtkLabel;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "gtk-label": LocalJSX.GtkLabel & JSXBase.HTMLAttributes<HTMLGtkLabelElement>;
        }
    }
}
